@startuml Diagrama Herança Cinema - Grupo 1
class Cinema{
    - razao_social: String
    - cnpj: Interger 
    - endereco: String
    - telefone: Interger
    - cep: Interger
    - email: String
    + construtor(razao_social, cnpj, endereco, telefone, cep, email)
    + contato(razao_social, telefone, email)
    + completa(razao_social, cnpj, endereco, telefone, cep, email)
}


class Sala{
    - num_sala: Interger
    - capacidade: Interger
    - assentos: Interger
    - ocupacao: Boolean
    + construtor(num_sala, capacidade, assentos, ocupacao)
    + alocacao_vendas(assentos, ocupacao)
    + capacidade_salas(num_sala, capacidade)
}

class Sessao{
    - data_sessao
    - hora_sessao
    - encerrada: Boolean
    - sala: Sala
    + construtor(data_sessao, hora_sessao, encerrada, sala)
    + sala_sessao(data_sessao, hora_sessao, sala)
    + situacao_sessao(encerrada, data_sessao, hora_sessao, sala)    
}

class Loja{
    - produtos: String
    - preco: Float
    - nota_fiscal: Interger
    + construtor(nota_fiscal, produtos, preco)
    + compra(nota_fiscal, produtos, preco)
    + tabela_precos(produtos, preco)
}

class Ingresso{
    - tipo: Interger
    - numero: Interger
    - preco_ingresso: Float
    - sessao: Sessao
    + construtor(tipo, numero, preco_ingresso, sessao)
    + tipo_ingresso(tipo, numero)
    + preco_ingresso(tipo, preco_ingresso, sessao)
}

class Cliente{
    - nome: String
    - cpf: Interger
    - data_nascimento: Interger
    - telefone: Interger
    - email: String
    - ingresso: Ingresso
    - compras: Loja
    + construtor(nome, cpf, data_nascimento, telefone, email, ingresso, compras)
    + contato_cliente(nome, telefone, email)
    + consumo_cliente(nome, email, ingresso, compras)    
}

class Filme{
    - titulo: String
    - genero: String
    - duracao: Time
    - classificacao: Interger
    + construtor(titulo, genero, duracao, classificacao, em_cartaz)
    + listar_filmes(titulo, em_cartaz)
    + classificacao(titulo, classificacao)
}

class Estreia{
    - titulo: String
    - duracao: Time
    - class_etaria: Interger
    - em_cartaz: Boolean
    + construtor(titulo, genero, duracao, class_etaria, em_cartaz)
    + listar_filmes(titulo, em_cartaz)
    + classif_etaria(titulo, class_etaria)
}

Cinema <|-- Sala
Sala --|> Sessao
Filme --|> Sessao
Ingresso <|-- Cliente
Cinema <|-- Loja
Loja <|-- Cliente
Sessao --|> Ingresso
@enduml