@startuml Diagrama Herança Cinema - Grupo 1

class Cinema {
    - razao_social: String
    - responsavel: String
    - cnpj: Interger 
    - endereco: String
    - telefone: Interger
    - cep: Interger
    - email: String
    + construtor(razao_social, resposavel, cnpj, endereco, telefone, cep, email)
    + contato(razao_social, responsavel, telefone, email)
    + cadastro completo(razao_social, responsavel, cnpj, endereco, telefone, cep, email)
}

class Sala{
    - num_sala: Interger
    - capacidade: Interger
    - assentos: Interger
    - ocupacao: Boolean
    + construtor(num_sala, capacidade, assentos, ocupacao)
    + alocacao_vendas(assentos, ocupacao)
    + capacidade_salas(num_sala, capacidade)
}

class Sessao{
    - data_sessao
    - hora_sessao
    - encerrada: Boolean
    - sala: Sala
    + construtor(data_sessao, hora_sessao, encerrada, sala)
    + sala_sessao(data_sessao, hora_sessao, sala)
    + situacao_sessao(encerrada, data_sessao, hora_sessao, sala)    
}